### ISSUE TITLE
Kerning in cyrillic italics

### ISSUE THREAD

**Issue by dom1n1k** [cyrealtype/Lora-Cyrillic#7]
Please see screenshots: Л**он**дон Санкт-П**ете**рбург Т**ок**ио.

[Google Fonts](https://fonts.google.com/specimen/Lora)
![fireshot screen capture 848](https://cloud.githubusercontent.com/assets/1683168/19136466/8e936d78-8b75-11e6-9e2d-87dedabf0c73.png)

[Webfont.ru](https://webfont.ru/font/lora)
![fireshot screen capture 850](https://cloud.githubusercontent.com/assets/1683168/19136472/97e28e4a-8b75-11e6-8f33-4d4126acc2dd.png)

**Comment by alexeiva** [comment]
This is fixed in https://github.com/cyrealtype/Lora-Cyrillic/commit/ba7b7bd863d14577ef89c72994472e2044b81447
Feel free to use latest TTFs from [here](https://github.com/cyrealtype/Lora-Cyrillic/tree/master/fonts).

<img width="715" alt="screen shot 2016-10-10 at 21 06 32" src="https://cloud.githubusercontent.com/assets/16634089/19255582/7895b2ae-8f2d-11e6-93c7-cf5437d58271.png">

As for the GF version, I suppose it will be updated some time.
